Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveMachoBraceIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with this\n"
    .string "MACHO BRACE.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedMachoBraceFromAide::
    .string "{PLAYER} received the MACHO BRACE\n"
    .string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainMachoBrace::
    .string "The MACHO BRACE doubles the\n"
    .string "EFFORT VALUES gained in battle.\p"
    .string "However, it lowers the holder's\n"
    .string "SPEED while it is being held.$"

